### ISSUE TITLE
ManyLinux shared objects as github release artifacts

### ISSUE THREAD

**Issue by andre2007** [open-simulation-platform/libcosimc#21]
It would be great if the github releases would contain prebuild static library / shared object (and include header ) for x86_64 linux.

If my understanding is correct release version of libcosimc.a is about 7 MB.

In the python world, static libraries/ shared objects are provided in a way that they are usable on many linux systems by building them on `CentOS 6`.

Github actions could be used here.

**Comment by andre2007** [comment]
I saw saw, the cosim4j package has almost all of the linux *.so / windows *.dll files.
libcosimc.so / libcosimc.dll is missing.

As it seems you already have a way to provide these files could you please provide them as a separate package including the libcosimc.h (libcosim C header file) and libcosimc.so / libcosimc.dll files?

**Comment by markaren** [comment]
These should be available as part of the conan distribution. cosim4j uses conan itself to get those.

https://github.com/open-simulation-platform/cosim4j/blob/master/cosim4j-native/conanfile.txt

Needs to be adapted if you also want the C libs.

**Comment by ljamt** [comment]
Created issue #23 and closing this one.
